# Generated by Django 5.0.3 on 2024-04-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stugender',
            field=models.CharField(default='not available', max_length=10),
        ),
    ]
