# Generated by Django 5.0.3 on 2024-04-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherid', models.IntegerField()),
                ('teachername', models.CharField(max_length=70)),
                ('teacheremail', models.EmailField(max_length=70)),
                ('teacherpass', models.CharField(max_length=70)),
            ],
        ),
    ]
